/**
 * Contributor email content. Rendering is pure so it can be tested; delivery
 * happens in the `notify-worker` function after the workflow change has been
 * committed (transactional outbox), with retries.
 */
import type { ContributorTemplate } from './workflow.ts';

export interface NotificationPayload {
    /** Absent for `submission_received`, which never repeats submitted text. */
    title?: string;
    reference: string | null;
    reason?: string | null;
    statusUrl: string;
    articleUrl?: string | null;
    recipientName?: string | null;
}

export interface RenderedEmail {
    subject: string;
    text: string;
}

export function renderNotification(template: ContributorTemplate | string, p: NotificationPayload): RenderedEmail {
    const ref = p.reference ? ` (${p.reference})` : '';
    const title = p.title ?? 'your submission';
    const greeting = p.recipientName ? `Dear ${p.recipientName},` : 'Hello,';
    const sign = '\n\nIT Museum Editorial Office\nChrist University, Bangalore Yeshwanthpur Campus';
    const status = `\n\nTrack your submission: ${p.statusUrl}`;
    switch (template) {
        case 'submission_received':
            // Fixed text: this email goes out before any human review, to an address
            // nobody has verified, so it carries no submitted text (title, names) —
            // even for rows queued before that payload was trimmed. The reference and
            // status link are generated by the server.
            return {
                subject: `IT Museum: submission received${ref}`,
                text: `Hello,\n\nThe IT Museum archive has received a research submission that gave this email address for updates. Its reference is ${p.reference ?? 'shown on the confirmation page'}. Keep this email: you need the reference and the access key shown after submission to check progress or send a revision.\n\nIf you did not submit anything, you can ignore this message; no account has been created for you.${status}${sign}`,
            };
        case 'changes_requested':
            return {
                subject: `Revision requested: ${title}${ref}`,
                text: `${greeting}\n\nThe review panel has asked for changes to "${title}" before it can continue.\n\nReviewer note:\n${p.reason ?? ''}\n\nPlease update your document and resubmit using the status page.${status}${sign}`,
            };
        case 'rejected':
            return {
                subject: `Decision on your submission: ${title}${ref}`,
                text: `${greeting}\n\nAfter review, the panel is unable to accept "${title}" for the IT Museum archive.\n\nReason:\n${p.reason ?? ''}${status}${sign}`,
            };
        case 'published':
            return {
                subject: `Published: ${title}${ref}`,
                text: `${greeting}\n\n"${title}" is now published in the IT Museum archive.${p.articleUrl ? `\n\nRead it here: ${p.articleUrl}` : ''}${sign}`,
            };
        case 'unpublished':
            return {
                subject: `Archive update: ${title}${ref}`,
                text: `${greeting}\n\n"${title}" has been temporarily withdrawn from the public archive by the editorial admin. We will contact you if anything is needed from you.${sign}`,
            };
        case 'revision_received':
            return {
                subject: `Revision received: ${title}${ref}`,
                text: `${greeting}\n\nWe have received your revised submission for "${title}". It has returned to the review stage that requested the changes.${status}${sign}`,
            };
        default:
            return { subject: `Update on ${title}${ref}`, text: `${greeting}\n\nThere is an update on your submission.${status}${sign}` };
    }
}

/** Exponential backoff for failed deliveries: 1, 5, 25, 125 minutes; give up after 5 attempts. */
export const MAX_NOTIFICATION_ATTEMPTS = 5;
export function nextAttemptDelayMinutes(attempts: number): number {
    return Math.pow(5, Math.max(0, attempts - 1));
}
